version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: narveer
      MYSQL_DATABASE: torontotime
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  toronto-app:
    build: .
    ports:
      - "8585:8585"
    depends_on:
      - mysql
